// generated by stringer -type=DynoState,DynoInput; DO NOT EDIT

package hsup

import "fmt"

const _DynoState_name = "StoppedStartedRetiringRetired"

var _DynoState_index = [...]uint8{0, 7, 14, 22, 29}

func (i DynoState) String() string {
	if i < 0 || i+1 >= DynoState(len(_DynoState_index)) {
		return fmt.Sprintf("DynoState(%d)", i)
	}
	return _DynoState_name[_DynoState_index[i]:_DynoState_index[i+1]]
}

const _DynoInput_name = "RetireRestartExitedStayStarted"

var _DynoInput_index = [...]uint8{0, 6, 13, 19, 30}

func (i DynoInput) String() string {
	if i < 0 || i+1 >= DynoInput(len(_DynoInput_index)) {
		return fmt.Sprintf("DynoInput(%d)", i)
	}
	return _DynoInput_name[_DynoInput_index[i]:_DynoInput_index[i+1]]
}
