#!/bin/bash
set -uex
PREFIX=${PREFIX:-tmp}
CEDAR_TARBALL=cedar-14.4.1.tgz
CEDAR_LOCAL_TARBALL="$PREFIX/$CEDAR_TARBALL"
NEWROOT="$PREFIX/root"
mkdir -p $NEWROOT

sudo umount $NEWROOT/tmp || true
sudo umount $NEWROOT/etc/resolv.conf || true
sudo umount $NEWROOT/etc/passwd || true
sudo unlink $NEWROOT/dev/urandom || true
sudo unlink $NEWROOT/dev/null || true

if ! [ -e "$CEDAR_LOCAL_TARBALL" ]; then
    curl "https://heroku-dan-bucket.s3.amazonaws.com/$CEDAR_TARBALL" > \
	"$CEDAR_LOCAL_TARBALL"
fi

tar -C "$NEWROOT" -zxf "$CEDAR_LOCAL_TARBALL"
touch "$NEWROOT/etc/resolv.conf"
sudo mount -t tmpfs -o size=200m tmpfs "$NEWROOT/tmp"

host_bind() {
    sudo mount --bind "$1" "$NEWROOT$1"
}

copy_device() {
    sudo cp -a "$1" "$NEWROOT$1"
}

host_bind /etc/resolv.conf
host_bind /etc/passwd
copy_device /dev/urandom
copy_device /dev/null
