#!/bin/sh
set -uex
CEDAR_TARBALL=cedar-14.4.1.tgz
CEDAR_LOCAL_TARBALL="tmp/$CEDAR_TARBALL"
NEWROOT="tmp/root"
mkdir -p tmp/root

sudo umount tmp/root/tmp || true
sudo umount tmp/root/etc/resolv.conf || true
sudo umount tmp/root/etc/passwd || true
sudo umount tmp/root/dev/urandom || true
sudo umount tmp/root/dev/null || true

if ! [ -e "$CEDAR_LOCAL_TARBALL" ]; then
    curl "https://heroku-dan-bucket.s3.amazonaws.com/$CEDAR_TARBALL" > \
	"tmp/$CEDAR_TARBALL"
fi

tar -C "$NEWROOT" -zxf "$CEDAR_LOCAL_TARBALL"
touch "$NEWROOT/etc/resolv.conf"
sudo mount -t tmpfs -o size=200m tmpfs "$NEWROOT/tmp"

host_bind() {
    sudo mount --bind "$1" "$NEWROOT$1"
}

host_bind /etc/resolv.conf
host_bind /etc/passwd
touch "$NEWROOT/dev/urandom"
host_bind /dev/urandom
touch "$NEWROOT/dev/null"
host_bind /dev/null
